REFRESCO/Antelope/Dev/Antelope/Models/HSE/ActionSecurite.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Antelope.Models.HSE
{
    public class ActionSecurite
    {

        public Int32 ActionSecuriteId { get; set; }

        public Int32 FicheSecuriteId { get; set; }

        [JsonIgnore]
        public virtual FicheSecurite FicheSecurite { get; set; }

        public String Code {get; set;}
        public String Description {get; set;}
        public String FaitPar { get; set; }

    }
}

REFRESCO/Antelope/Dev/Antelope/Models/HSE/CorpsHumainZone.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Antelope.Models.HSE
{
    public class CorpsHumainZone
    {
        public Int32 Id { get; set; }

        public string Nom { get; set; }
        public string Code { get; set; }

        // Virtual = Lazy Loading
        [JsonIgnore]
        public virtual List<FicheSecurite> FicheSecurites { get; set; }
    }
}

REFRESCO/Antelope/Dev/Antelope/Models/HSE/Danger.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Antelope.Models.HSE
{
    public class Danger
    {
        public Int32 DangerID { get; set; }

        public string Nom { get; set; }

        // Virtual = Lazy Loading
        [JsonIgnore]
        public virtual List<FicheSecurite> FicheSecurites { get; set; }

    }
}

REFRESCO/Antelope/Dev/Antelope/Models/HSE/DialogueSecuriteParams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http.ModelBinding;

using Antelope.Binders;

using Newtonsoft.Json;

namespace Antelope.Models.HSE
{
    /// <summary>
    /// Paramètres du filtre de la liste des dialogues sécurités.
    /// </summary>
    [ModelBinder(typeof(JsonDatatableBinder))]
    [JsonObject(MemberSerialization.OptOut)]
    public class DialogueSecuriteParams : JsonDatatable
    {
        public int SiteId { get; set; }
        public string Atelier { get; set; }

        public DateTime? DateDebut { get; set; }
        public DateTime? DateFin { get; set; }

    }
}

REFRESCO/Antelope/Dev/Antelope/Models/HSE/RisqueType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace Antelope.Models.HSE
{
    public class RisqueType
    {
        public Int32 RisqueTypeId { get; set; }

        public string Nom { get; set; }

        [JsonIgnore]
        public virtual List<Risque> Risques { get; set; }

    }
}

REFRESCO/Antelope/Dev/Antelope/Controllers/API/HSE/ActiveDirectoryUtilisateurController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using Antelope.Domain.Models;
using Antelope.ViewModels.Socle.ActiveDirectory;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices;

using Antelope.Configurations;
using Antelope.Infrastructure.EntityFramework;

namespace Antelope.Controllers.API.HSE
{
    public class ActiveDirectoryUtilisateurController : ApiController
    {
        private AntelopeEntities db = new AntelopeEntities();



        public HttpResponseMessage GetActiveDirectoryUtilisateurByNomPrenom(int id, string param1, string param2)  // [FromUri] ActiveDirectoryUtilisateurViewModel activeDirectoryUtilisateurViewModel
        {

            List<ActiveDirectoryUtilisateurViewModel> allActiveDirectoryViewModel = new List<ActiveDirectoryUtilisateurViewModel>();
            List<Guid> AllGuid = new List<Guid>();
            List<Personne> AllPersonne = new List<Personne>();

            var context = new PrincipalContext(ContextType.Domain, ActiveDirectoryConfig.CurrentConfig.DomainName); //"refresco.local" > Pas obligatoire ?
            //define a "query-by-example" principal - here, we search for a UserPrincipal 
            //and with the first name (GivenName) and a last name (Surname) 
            UserPrincipal qbeUser = new UserPrincipal(context);

            if(param2 != "undefined"){
                qbeUser.GivenName = "*" + param2 + "*";
            }
            if (param1 != "undefined")
            {
                qbeUser.Surname = "*" + param1 + "*";
            }

            // create your principal searcher passing in the QBE principal    
            PrincipalSearcher srch = new PrincipalSearcher(qbeUser);


            // find all matches
            foreach (var result in srch.FindAll())
            {
                DirectoryEntry de = result.GetUnderlyingObject() as DirectoryEntry;
                System.Diagnostics.Debug.WriteLine("First Name: " + de.Properties["givenName"].Value + " " + "Last Name : " + de.Properties["sn"].Value);

                allActiveDirectoryViewModel.Add(
                    new ActiveDirectoryUtilisateurViewModel
                    {
                        Nom = (string)de.Properties["sn"].Value,
                        Prenom = (string)de.Properties["givenName"].Value,
                        Guid = (Guid)result.Guid,
                        IsAnnuaireAD = true,
                        IsAnnuaireApplication = false
                    }
                );

                AllGuid.Add((Guid)result.Guid);
            }


            var queryPersonne = from p in db.Personnes
                                where AllGuid.Contains(p.Guid)
                                || ((param1 == "undefined" || p.Nom.Contains(param1))
                                && (param2 == "undefined" || p.Prenom.Contains(param2)))
                                select p;

            //var queryPersonne = from p in db.Personnes
            //                    where  p.Nom.Contains(param1)
            //                    select p;

            AllPersonne = queryPersonne.ToList();

            foreach (ActiveDirectoryUtilisateurViewModel activeDirectoryViewModel in allActiveDirectoryViewModel)
            {
                //Itération déscendante afin de pouvoir couper la branche sur laquelle on est (remove de la Personne)
                for (int i = AllPersonne.Count - 1; i >= 0; --i)
                {
                    if (AllPersonne[i].Guid == activeDirectoryViewModel.Guid)
                    {
                        activeDirectoryViewModel.PersonneId = AllPersonne[i].PersonneId;
                        activeDirectoryViewModel.IsAnnuaireApplication = true;
                        AllPersonne.RemoveAt(i);
                    }
                }
            }

            foreach (Personne personne in AllPersonne)
            {
                allActiveDirectoryViewModel.Add(new ActiveDirectoryUtilisateurViewModel()
                {
                    PersonneId = personne.PersonneId,
                    Nom = personne.Nom,
                    Prenom = personne.Prenom,
                    Guid = personne.Guid,
                    IsAnnuaireAD = false,
                    IsAnnuaireApplication = true
                });
            }

            //if(param2 != "undefined"){
            //    queryPersonne.Where(p => AllGuid.Contains(p.Guid) ||
                    
            //        (param2 != "undefined") ? p.Nom.Contains(param2):true);
            //};

            //         from i in dc.SomeTable
            //  where (a == "" || i.A.Contains(a))
            //    && (b == "" || i.B.Contains(b))
            //    && (c == "" || i.C.Contains(c))
            //  select i;

            //...and if you want to switch from 'and' to 'or' between the different predicates, just change it to:

            //var results =
            //  from i in dc.SomeTable
            //  where (a == "" || i.A.Contains(a))
            //    || (b == "" || i.B.Contains(b))
            //    || (c == "" || i.C.Contains(c))
            //  select i;







            //POUR TEST LOCAL SANS Active Directory, NE PAS EFFACER MERCI
            //allActiveDirectoryViewModel.Add(
            //    new ActiveDirectoryUtilisateurViewModel
            //    {
            //        Nom = "Boyer",
            //        Prenom = "Julien",
            //        Guid = new Guid()
            //    }
            //);


            return Request.CreateResponse(HttpStatusCode.OK, allActiveDirectoryViewModel);
        }

    }
}

REFRESCO/Antelope/Dev/Antelope/Controllers/API/HSE/DialogueSecuriteController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;

using Antelope.Domain.Models;
using Antelope.Infrastructure.EntityFramework;
using Antelope.Models.HSE;
using Antelope.Repositories.HSE;
using Antelope.Repositories.Socle;
using Antelope.Services.HSE;
using Antelope.Services.Socle;
using Antelope.ViewModels.HSE.DialogueSecuriteViewModels;
using Antelope.ViewModels.Socle.DataTables;

namespace Antelope.Controllers.API.HSE
{
    public class DialogueSecuriteController : ApiController
    {

        public DialogueSecuriteRepository _dialogueSecuriteRepository { get; set; }
        public ActiveDirectoryUtilisateurRepository _activeDirectoryUtilisateurRepository { get; set; }
        private AntelopeEntities db = new AntelopeEntities();
        private PersonneAnnuaireService _personneAnnuaireService { get; set; }
        private EmailService _emailService { get; set; }

        public DialogueSecuriteController()
        {
            _personneAnnuaireService = new PersonneAnnuaireService(db);
            _emailService = new EmailService();
            _dialogueSecuriteRepository = new DialogueSecuriteRepository();
        }


        public HttpResponseMessage Get(DialogueSecuriteParams dialogueSecuriteParams)
        {
            DataTableViewModel<DialogueSecuriteModel> dataTableViewModel = _dialogueSecuriteRepository.GetFromParams(dialogueSecuriteParams);
            return Request.CreateResponse(HttpStatusCode.OK, dataTableViewModel);
        }

        [ResponseType(typeof(DialogueSecurite))]
        public HttpResponseMessage Get(int id)
        {
            _activeDirectoryUtilisateurRepository = new ActiveDirectoryUtilisateurRepository();
            _dialogueSecuriteRepository = new DialogueSecuriteRepository();

            DialogueSecurite dialogueSecurite;
            List<Zone> allZone;
            List<Lieu> allLieu;

            if (id == -1)
            {
                Site SiteUser = _activeDirectoryUtilisateurRepository.GetCurrentUserSite();

                dialogueSecurite = new DialogueSecurite()
                {
                    SiteId = (SiteUser == null) ? 0 : SiteUser.SiteID
                };

                var queryZone = from a in db.Zones
                                where a.SiteId == SiteUser.SiteID
                                select a;
                allZone = queryZone.ToList();

                allLieu = new List<Lieu>(); 
            }
            else
            {
                dialogueSecurite = _dialogueSecuriteRepository.Get(id);

                if (dialogueSecurite == null)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                var queryZone = from a in db.Zones
                                where a.SiteId == dialogueSecurite.SiteId
                                select a;
                allZone = queryZone.ToList();

                var queryLieu = from a in db.Lieux
                                where a.ZoneId == dialogueSecurite.ZoneId
                                orderby a.Rang
                                select a;
                allLieu = queryLieu.ToList();
            }

            var dialogueSecuriteViewModel = new DialogueSecuriteViewModel(dialogueSecurite, allZone, allLieu);
            return Request.CreateResponse(HttpStatusCode.OK, dialogueSecuriteViewModel);
        }

        [ResponseType(typeof(void))]
        public HttpResponseMessage Put(int id, DialogueSecurite dialogueSecurite)
        {
            if (!ModelState.IsValid)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }

            if (id != dialogueSecurite.Id)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }


            var currentdialogueSecurite = db.DialogueSecurites.Find(dialogueSecurite.Id);
            db.Entry(currentdialogueSecurite).CurrentValues.SetValues(dialogueSecurite);

            db.Entry(currentdialogueSecurite).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DialogueSecuriteExists(id))
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound, currentdialogueSecurite);
                }
                else
                {
                    throw;
                }
            }

            return Request.CreateResponse(HttpStatusCode.OK, currentdialogueSecurite);
        }


        public HttpResponseMessage Post(DialogueSecurite dialogueSecurite)
        {
            // DialogueSecurite.DateCreation = DateTime.Now;

            dialogueSecurite.CompteurAnnuelSite = 1;

            var QueryLastDialogueSecuriteForSiteAnnee = from ds in db.DialogueSecurites
                                                        where ds.SiteId == dialogueSecurite.SiteId
                                                     && ds.Date.Year == dialogueSecurite.Date.Year
                                                        orderby ds.CompteurAnnuelSite descending
                                                        select ds;

            DialogueSecurite LastDialogueSecuriteForSiteAnnee = QueryLastDialogueSecuriteForSiteAnnee.FirstOrDefault();

            if (LastDialogueSecuriteForSiteAnnee != null)
            {
                if (LastDialogueSecuriteForSiteAnnee.Date.Year == dialogueSecurite.Date.Year)
                {
                    dialogueSecurite.CompteurAnnuelSite = LastDialogueSecuriteForSiteAnnee.CompteurAnnuelSite + 1;
                }
            }

            Site site = db.Sites.First(s => s.SiteID == dialogueSecurite.SiteId);
            dialogueSecurite.Code += site.Trigramme + "-" + dialogueSecurite.Date.Year + "-" + dialogueSecurite.CompteurAnnuelSite;

            dialogueSecurite.Dialogueur1 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Dialogueur1.Nom, dialogueSecurite.Dialogueur1.Prenom, dialogueSecurite.Dialogueur1Id, db
            );
            dialogueSecurite.Dialogueur2 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Dialogueur2.Nom, dialogueSecurite.Dialogueur2.Prenom, dialogueSecurite.Dialogueur2Id, db
            );
            dialogueSecurite.Dialogueur3 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Dialogueur3.Nom, dialogueSecurite.Dialogueur3.Prenom, dialogueSecurite.Dialogueur3Id, db
            );
            dialogueSecurite.Entretenu1 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Entretenu1.Nom, dialogueSecurite.Entretenu1.Prenom, dialogueSecurite.Entretenu1Id, db
            );
            dialogueSecurite.Entretenu2 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Entretenu2.Nom, dialogueSecurite.Entretenu2.Prenom, dialogueSecurite.Entretenu2Id, db
            );
            dialogueSecurite.Entretenu3 = _personneAnnuaireService.GetPersonneFromAllAnnuaireOrCreate(
                dialogueSecurite.Entretenu3.Nom, dialogueSecurite.Entretenu3.Prenom, dialogueSecurite.Entretenu3Id, db
            );

            db.DialogueSecurites.Add(dialogueSecurite);

            //try
            //{
            db.SaveChanges();
            DialogueSecurite dbDialogueSecurite = db.DialogueSecurites
                .Where(ds => ds.Id == dialogueSecurite.Id)
                .Include(ds => ds.Thematique)
                .Include(ds => ds.ServiceType)
                .Include(ds => ds.ServiceType1)
                .Include(ds => ds.ServiceType2)
                .Include(ds => ds.ServiceType3)
                .Include(ds => ds.ServiceType4)
                .Include(ds => ds.ServiceType5)
                .FirstOrDefault();

            _emailService.SendEmailDiffusionDialogueSecurite(dbDialogueSecurite);
            return Request.CreateResponse(HttpStatusCode.OK, dbDialogueSecurite);
            //}
            //catch (Exception e)
            //{
            //    return Request.CreateResponse(HttpStatusCode.InternalServerError, e);
            //}

        }

        public HttpResponseMessage Delete(int id)
        {
            DialogueSecurite dialogueSecurite = db.DialogueSecurites.Find(id);
            if (dialogueSecurite == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.DialogueSecurites.Remove(dialogueSecurite);
            db.SaveChanges();

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool DialogueSecuriteExists(int id)
        {
            return db.DialogueSecurites.Count(e => e.Id == id) > 0;
        }
    }
}

REFRESCO/Antelope/Dev/Antelope/Views/HSE/HSEHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/HSE/Shared/_Layout.cshtml";
}

<style type="text/css">
    body {
        background-repeat: no-repeat;
        background-position: center center;
        background-size: 90% 100%;
        background-attachment: fixed;
        background-image: url(/Content/images/FOND_INTRANET_SANS_POMME.jpg);
    }
</style>

<script type="text/javascript" src="/Scripts/spin.min.js"></script>


<div class="row">
    <div class="col-md-4">

    </div>
    <div class="col-md-4">
        <div class="panel panel-danger" >
            <div class="panel-heading" style="background-color: #C42031; color: white">SECURITE</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-8">
                        <a href="#" class="thumbnail">
                            <img src="~/Content/images/HSE/Home/PICTO_securite.png" alt="...">
                        </a>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Liste des Fiches Sécurité", "Index", "FicheSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #C42031; color: white;" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Nouvelle Fiche Sécurité", "Create", "FicheSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #C42031; color: white" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Liste des Dialogues Sécurité", "Index", "DialogueSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #C42031; color: white" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Nouveau Dialogue Sécurité", "Create", "DialogueSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #C42031; color: white" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Evaluation des risques", null, null, null, new { @class = "btn-lg btn-default"})
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("Statistiques", "Index", "HSEStatistique", null, new { @class = "btn-lg btn-danger", @style = "background-color: #C42031; color: white" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-success">
            <div class="panel-heading" style="background-color: #8BAC27; color: white">ENVIRONNEMENT</div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-md-2">
                    </div>
                    <div class="col-md-8">
                        <a href="#" class="thumbnail">
                            <img src="~/Content/images/HSE/Home/PICTO_environnement.png" alt="...">
                        </a>
                    </div>
                    <div class="col-md-2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("A Venir", "Index", "FicheSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #8BAC27; color: white;" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10 text-center">
                        @Html.ActionLink("A Venir", "Create", "FicheSecurite", null, new { @class = "btn-lg btn-danger", @style = "background-color: #8BAC27; color: white" })
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
                <br />
                <br />
                <br /> 
            </div>
        </div>
    </div> 
</div>
 
<br/>
<br />
<br />
<br />
<br />
<br />